//! Emit a golden Q4_K / Q6_K / Q5_0 fixture for minglang's `kernels-sys::kquant` tests.
//!
//! minglang consumes the bytes this crate writes. Hand-computed tests on both sides can agree
//! with each other and still disagree on the format, so the kernel's real oracle is this
//! crate's output — which is itself bit-exact with the pinned ggml oracle.
//!
//! `cargo run -p requant-quant --example emit_kquant_fixture > fixture.rs`

fn main() {
    // Deterministic pseudo-random row with a realistic weight distribution: a few outliers so
    // the per-sub-block scale search actually has something to do.
    let n = 512usize;
    let mut s = 0x2545_F491_4F6C_DD1Du64;
    let x: Vec<f32> = (0..n)
        .map(|i| {
            s ^= s << 13;
            s ^= s >> 7;
            s ^= s << 17;
            let u = (s >> 40) as f32 / 16777216.0 - 0.5;
            if i % 97 == 0 {
                u * 6.0
            } else {
                u * 0.4
            }
        })
        .collect();

    println!("// @generated by requant-quant/examples/emit_kquant_fixture.rs — do not edit.");
    println!("// requant is bit-exact with the pinned ggml oracle; this pins minglang to requant.");
    println!("pub const N: usize = {n};");
    emit("X", "f32", &x.iter().map(|v| format!("{v:?}")).collect::<Vec<_>>());

    for (name, ty, cols) in [("Q4K", 12u32, n), ("Q6K", 14, n), ("Q5_0", 6, n), ("Q8_0", 8, n)] {
        let bytes = requant_quant::quantize_tensor(ty, &x, 1, cols, None).unwrap();
        let deq = requant_quant::dequantize_tensor(ty, &bytes, 1, cols).unwrap();
        emit(
            &format!("{name}_BYTES"),
            "u8",
            &bytes.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>(),
        );
        emit(
            &format!("{name}_DEQ"),
            "f32",
            &deq.iter().map(|v| format!("{v:?}")).collect::<Vec<_>>(),
        );
    }
}

fn emit(name: &str, ty: &str, items: &[String]) {
    println!("pub const {name}: [{ty}; {}] = [", items.len());
    for chunk in items.chunks(8) {
        println!("    {},", chunk.join(", "));
    }
    println!("];");
}
